 # NUMPY:


## checking the version of numpy

In [1]:
#first import the numpy library
import numpy as np

In [2]:
np.__version__

'1.22.2'

### Creating our first array 


In [3]:
# creating a array full of zeros
np.zeros([5,2])  # by 5,2  means 5 rows and 2 colums

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
# creating a array full of ones
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### Creating our 1D own array

In [5]:
a = np.arange(1,20) # with this arrange function you can create your own array

In [6]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

##### Want to access the array specific elemet

In [7]:
a[3] # in python the index starts with 0

4

#### Want to add an element in the array

In [8]:
# We will use numpy append function to add an element to the array.
new=np.append(a,20)

In [9]:
new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

###### Want to see the data type of an array

In [10]:
a.dtype

dtype('int32')

###### Want to see the shape of array

In [11]:
a.shape

(19,)

## Math operation on  2D arrays

In [12]:
# lets create first 2 arrays
c=np.array([[1,2,3,],[3,4,5],[7,8,9]])
d=np.array([[1,2,3,],[3,4,5],[7,8,9]])

In [13]:
print(c,d)

[[1 2 3]
 [3 4 5]
 [7 8 9]] [[1 2 3]
 [3 4 5]
 [7 8 9]]


## checking the dimension of array

In [14]:
np.ndim(c)

2

In [15]:
np.shape(c) # to perform these opertion on array. array shape and dimension should be same 

(3, 3)

In [16]:
add=np.add(c,d) # .add is numpy function to add two array

In [17]:
add

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [14, 16, 18]])

In [18]:
# subtraction of array
sub=np.subtract(c,d) # .subtract is numpy function to subtract two array

In [19]:
sub

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
# multiplycation of an array
mul=np.multiply(c,d) # .multiply is numpy function to multiply two array

In [21]:
mul

array([[ 1,  4,  9],
       [ 9, 16, 25],
       [49, 64, 81]])

In [22]:
# divison of array
div=np.divide(c,d) # .divide is numpy function to divide two array

In [23]:
div

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## sorting of array

In [24]:
# lets just create simple array 
g=np.array([2,58,68,58,95,8,5,8])

In [25]:
np.sort(g) # SORT FUNCTION IN NUMPY TO SORT AN ARRRAY

array([ 2,  5,  8,  8, 58, 58, 68, 95])

## Want an array with evenly spaced numbers over a specified interval

In [26]:
# In numpy we have a function call linspace
np.linspace(0,100, num=15) # by 0,100,15 means  the array should start from 0 and ends on 100 the samples we want =15

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

## Array with the given shape, dtype, and order.

In [27]:
np.full((2,2),112,)

array([[112, 112],
       [112, 112]])

## For more details check numpy website
 https://numpy.org/doc/stable/user/absolute_beginners.html